name: On release
on:
    release:
        types: [released]
jobs:
  resources:
    name: Update wp theme version
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v6

        - uses: actions/setup-node@v6

        - name: Update version
          run: python ./.github/workflows/update_version.py ${{ github.event.release.name }}

        - name: Update wp theme version
          uses: test-room-7/action-update-file@v2
          with:
              file-path: |
                style.css
                CHANGELOG.md
              commit-msg: Update wp theme version
              github-token: ${{ secrets.GITHUB_TOKEN }}
        - name: Zip Folder
          run: zip -r ${{ github.event.repository.name }}.zip . -x ".git/*" ".github/*" "phpcs.xml" "composer.json" "composer.lock" ".gitignore" "CHANGELOG.md" "README.md" "*.code-workspace" "*.cmd"

        - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: ${{ github.event.repository.name }}.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}